services:
  - type: web
    name: qhorizonpm
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://your-domain
      - key: APP_LOCALE
        value: vi
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: qhorizonpm-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: qhorizonpm-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: qhorizonpm-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: qhorizonpm-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: qhorizonpm-db
          property: password
      - key: RUN_MIGRATIONS
        value: "true"
      - key: RUN_SEED
        value: "false"

databases:
  - name: qhorizonpm-db
    plan: free
